# -*- coding: utf-8 -*-
"""nural network.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UrGfAKhT9uz3R3yXK3RgEALA0MlfhpYo
"""

from bs4 import BeautifulSoup
import requests
import re

response = requests.get(
    "http://www.nigeria-law.org/ConstitutionOfTheFederalRepublicOfNigeria.htm"
)
root = BeautifulSoup(response.content, "lxml")
constitution_words = re.sub(r"\s+"," ", root.text) # replace whitespaces with a single space

constitution_words



"""## Tokenization

### Sentence Tokenization
"""

root.text

' The boy  '.strip()

constitution_lines = [re.sub(r"\s+"," ", line).strip() for line in root.text.split("\n") if line.strip()]
constitution_lines[50:100]

constitution_lines = [re.sub(r'\d+', '', line.lower())
                    for line in constitution_lines if len(line.split()) > 3]

constitution_lines[50:100]



"""### Word Tokenization"""

wt_constitution_lines = [sentence.split() for sentence in constitution_lines]
wt_constitution_lines[50:100]

import nltk
from nltk.tokenize import word_tokenize
import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

nltk.download('punkt')
nltk.download('punkt_tab') # Download the missing resource

text = "Hello, world! How's it going?"
tokens = word_tokenize(text)
print(tokens)

import nltk
from nltk.tokenize import word_tokenize
import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

nltk.download('punkt')
nltk.download('punkt_tab') # Download the missing resource

wt_constitution_lines = [word_tokenize(sentence) for sentence in constitution_lines]
wt_constitution_lines[50:100]



"""### Character Tokenization

In this case, the goal is to split the sentences into individual characters. One easy way to do that is to use the list constructor.
"""

ct_constitution_lines = [list(sentence) for sentence in constitution_lines]
print(ct_constitution_lines[50])



"""Notable Mention: Subword Tokenisation
For some languages, English included, it is useful to break down words into smaller units. This is particularly useful when dealing with compound words (e.g. "Irregardless" which can be broken down into "Ir", "regard" and "less")or when dealing with out-of-vocabulary words. Techniques like Byte-Pair Encoding (BPE) and WordPiece are popular subword tokenization methods.

BPE in particular works by splitting words into smaller, more frequent units. This makes it easier for it to handle rare words and out-of-vocabulary terms by decomposing them into familiar subword units.
"""

"author"  "is" "a" "tion"
"author" "i" "ty"

!pip install sentencepiece

with open('data.txt', 'w') as f:
    f.write('\n'.join(constitution_lines))

import sentencepiece as spm

# Train
spm.SentencePieceTrainer.train(input='data.txt', model_prefix='m', vocab_size=2000)

sp = spm.SentencePieceProcessor(model_file='m.model')

# Known word
word = "constitution"
tokens = sp.EncodeAsPieces(word)
print(f"{word}: {tokens}")

# Unknown word
word = "restitution"
tokens = sp.EncodeAsPieces(word)
print(f"{word}: {tokens}")

sp.EncodeAsPieces("subordinate jurisdiction to that of a High Court;")



"""### Visualizing Text Data

##### Character Histogram


"""

import numpy as np
import matplotlib.pyplot as plt
from tqdm.auto import tqdm

separate_characters = list(''.join(constitution_lines))
character_frequency = np.unique(separate_characters, return_counts=True)

plt.figure(figsize=(10, 15))
plt.barh(character_frequency[0], character_frequency[1], )



"""#### Word Histogram"""

new_constitution_words = ' '.join(constitution_lines)
word_frequency = np.unique(new_constitution_words.split(), return_counts=True)

word_frequency[1].shape

plt.barh(word_frequency[0], word_frequency[1])



"""#### Word Cloud"""

new_constitution_words

from wordcloud import WordCloud

wc = WordCloud(width=1200, height=400, max_words=6000, random_state=42).generate(new_constitution_words)
wc.to_image()



"""#### Vectorization"""

import gensim as gs
from gensim import corpora
from gensim.models import TfidfModel

# Create a dictionary from the tokenized sentences
dictionary = corpora.Dictionary(wt_constitution_lines)

# Convert tokenized sentences into bag-of-words format
bow_corpus = [dictionary.doc2bow(sentence) for sentence in wt_constitution_lines]

# Create a TF-IDF model
tfidf_model = TfidfModel(bow_corpus)

# Get TF-IDF vectors
tfidf_vectors = [tfidf_model[bow] for bow in bow_corpus]



!pip install gensim

# Display results
idx = 42
sentence = wt_constitution_lines[idx]
print("Sentence:", sentence)
for word_id, score in tfidf_vectors[idx]:
    print(f"{dictionary[word_id]}: {score:.4f}")

sample_idx_1 = 42
sample_idx_2 = 73

print(f"Sentence 1: {' '.join(wt_constitution_lines[sample_idx_1])}")
print(f"Sentence 2: {' '.join(wt_constitution_lines[sample_idx_2])}")

similarity = gs.matutils.cossim(
    vec1=tfidf_vectors[sample_idx_1],
    vec2=tfidf_vectors[sample_idx_2],
)
print(similarity)



"""### Word Embeddings"""

!gdown 0B7XkCwpI5KDYNlNUTTlSS21pQmM

!gunzip GoogleNews-vectors-negative300.bin.gz

from gensim.models import KeyedVectors

# Loading pre-trained word embeddings
word_vectors = KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin', binary=True)

def get_gensim_embeddings(wt_sentence):
    embeddings = []
    for word in wt_sentence:
        if word in word_vectors:
            embeddings.append(word_vectors[word])
    return embeddings

gensim_embeddings = get_gensim_embeddings(wt_constitution_lines[0])
print(np.shape(gensim_embeddings))



"""### Word Similarity"""

def gensim_similarity(word1, word2):
    if word1 in word_vectors and word2 in word_vectors:
        return word_vectors.similarity(word1, word2)
    return 0

print(gensim_similarity("love", "hate"))

print(gensim_similarity("constitution", "law"))

gensim_similarity('atoms','electrons')



"""### Visualizing Embeddings"""

selected_words = ["love", "hate", "natural", "artificial", "language", "word", "computer", "book", "paper", "constitution", "law"]
word_embeddings = np.array([word_vectors[word] for word in selected_words if word in word_vectors])
word_embeddings.shape

from sklearn.manifold import TSNE

def visualize_embeddings_2D(selected_words, word_embeddings, word_vectors):
    # Project embeddings into 2D using t-SNE
    tsne = TSNE(n_components=2, random_state=42, learning_rate='auto', perplexity=3)
    word_2d_embeddings = tsne.fit_transform(word_embeddings)

    plt.figure(figsize=(8, 8))
    for i, word in enumerate(selected_words):
        if word in word_vectors:
            plt.scatter(word_2d_embeddings[i, 0], word_2d_embeddings[i, 1], marker='+', color='red')
            plt.text(word_2d_embeddings[i, 0]+0.2, word_2d_embeddings[i, 1], word, fontsize=9)
    plt.show()

visualize_embeddings_2D(selected_words, word_embeddings, word_vectors)



"""### Comparing sentences"""

sentence1 = word_tokenize("Right to freedom of expression and the press.".lower())
sentence2 = word_tokenize("Right to freedom from discrimination.".lower())
word_vectors.n_similarity(sentence1, sentence2)

sentence1 = word_tokenize("Right to freedom of expression and the press.".lower())
sentence2 = word_tokenize("secure full residence rights for every citizen in all parts of the Federation.".lower())
word_vectors.n_similarity(sentence1, sentence2)



"""### SpaCy"""

